name: Deploy Demo

on:
  push:
    branches:
      - "main"

env:
  IMAGE: foxfurry/gha-demo-public:${{ github.sha }}

jobs:
  build_and_push_container:
    name: Build and Push Docker Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build Server Binary
        working-directory: deploy-demo
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/demo.bin main.go

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: deploy-demo
          push: true
          tags: ${{ env.IMAGE }}
