name: Static Checks Demo

on:
  push:
    branches:
      - "*"

jobs:
  my_first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: Cheese
        run: |
          echo "Cheese!"
          echo "The shell is $SHELL"

  linter:
    name: Lint Golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: static-demo

